name: Deploy Zendesk App to SB1

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: zendesk/checkout@v2

      - name: Add ZAT Config
        env:
          ZAT_UAT: ${{ secrets.ZAT_SB1 }}
        run: |
          echo $ZAT_SB1 >> .zat

      - name: ZAT Deploy
        uses: zendesk/zat-deploy@master
