name: Deploy Zendesk App to MyDev

on:
  push:
    branches: [uat]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: zendesk/checkout@v2

      - name: Add ZAT Config
        env:
          ZAT_DEV: ${{ secrets.ZAT_MYDEV }}
        run: |
          echo $ZAT_MYDEV >> .zat

      - name: My Test
        run: |
          pwd
          ls -la

      - name: ZAT Deploy
        uses: zendesk/zat-deploy@master
